### ISSUE TITLE
Parsed floats are truncated

### ISSUE THREAD

**Issue by jait** [Tumetsu/kilometrikisa-client#21]
When scraping the data from html, the floats are truncated. This seems to be because (at least for me) the data on the website is in Finnish format (with comma, e.g. "35,2") and `parseFloat()` truncates these to integers. In order to get correct result with decimals, these values would have to formatted first so that "," is replaced with ".".

**Comment by jait** [comment]
PR with a possible fix: https://github.com/Tumetsu/kilometrikisa-client/pull/22

**Comment by Tumetsu** [comment]
PR merged and new version of the package (0.13.4) released in NPM.
